### ISSUE TITLE
Tested Grayskull™ e75 and get an exception (looks somehow **critical**)

### ISSUE THREAD

**Issue by jaebaek** [tenstorrent/tt-kmd#21]
I purchased Grayskull™ e75 and install the hardware.
I followed steps described [here](https://docs.tenstorrent.com/tenstorrent/v/tt-buda/installation#installation-prerequisites).
I think I followed it correctly because I can see the following results:

```
$ ls /dev/tenstorrent/
0
$ find /lib/modules/$(uname -r) -type f -name '*.ko' | grep 'tens'
/lib/modules/5.15.0-107-generic/updates/dkms/tenstorrent.ko
/lib/modules/5.15.0-107-generic/kernel/sound/soc/sof/xtensa/snd-sof-xtensa-dsp.ko
/lib/modules/5.15.0-107-generic/kernel/sound/soc/xtensa/snd-soc-xtfpga-i2s.ko
```

but the firmware installation failed:

```
 $ sudo apt install cargo
 $ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
 $ source "$HOME/.cargo/env"
 $ python -m venv venv
 $  python3 -m venv venv
 $  source venv/bin/activate
 $  pip install git+https://github.com/tenstorrent/tt-flash.git
 $  tt-flash -h
 $  git clone https://github.com/tenstorrent/tt-firmware.git

# Now I have the problem
$  tt-flash flash --fw-tar tt-firmware/latest.fwbundle 
 $  tt-flash flash --fw-tar tt-firmware/fw_pack-80.8.0.0.fwbundle 
 $  tt-flash flash --fw-tar tt-firmware/patches/fw_pack-80.8.11.0.fwbundle
$  tt-flash flash --fw-tar tt-firmware/patches/fw_pack-80.8.12.0.fwbundle
```

The last 4 commands all failed with the following message:
```
Traceback (most recent call last):
  File "/home/jaebaek/tt-kmd-ttkmd-1.27.1/venv/bin/tt-flash", line 8, in <module>
    sys.exit(main())
  File "/home/jaebaek/tt-kmd-ttkmd-1.27.1/venv/lib/python3.8/site-packages/tt_flash/main.py", line 195, in main
    rc += flash_chip(
  File "/home/jaebaek/tt-kmd-ttkmd-1.27.1/venv/lib/python3.8/site-packages/tt_flash/flash.py", line 242, in flash_chip
    raise TTError(
tt_flash.error.TTError: Looks like you are running a very old set of fw, it's safe to assume that it needs an update but please update it using --force
```

I printed the versions at [this line](https://github.com/tenstorrent/tt-flash/blob/aceef7ddda4b83098c90626d48ef77f8ef444277/tt_flash/flash.py#L196):
```
fw_version: 
16842752
chip.min_fw_version(): 
17104896
```

For all `tt-firmware/latest.fwbundle , tt-firmware/fw_pack-80.8.0.0.fwbundle, tt-firmware/patches/fw_pack-80.8.11.0.fwbundle, tt-firmware/patches/fw_pack-80.8.12.0.fwbundle`, I got the same `fw_version` lower than `chip.min_fw_version()`.

The error message recommends me to use `--force`, but I am worried about side effects.

I would appreciate any help!

**Comment by alewycky-tenstorrent** [comment]
--force may be required for some firmware upgrades, please see https://docs.tenstorrent.com/tenstorrent/add-in-boards-and-cooling-kits/grayskull-tm-e75-e150/software-setup#update-firmware where this situation is mentioned.

**Comment by jaebaek** [comment]
Thanks!
